bindkey -e  # emacs mode key bindings

## Profiling
zmodload zsh/zprof
profile_zsh_init () {
    for i in $(seq 1 10); do /usr/bin/time /usr/local/bin/zsh -i -c exit; done;
}

## Modules
fpath+=~/.zfunc
autoload -Uz compinit && compinit

## Extra Scripts
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh  # https://github.com/junegunn/fzf
[ -f ~/.git-prompt.sh ] && source ~/.git-prompt.sh  # https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh

## Options
setopt auto_cd         # change directories without typing cd
setopt prompt_subst    # prompt string is first subjected to parameter expansion, command substitution and arithmetic expansion
setopt append_history  # allow multiple terminal sessions to all append to one zsh command history

## Environment
cdpath=($HOME/projects)
export EDITOR=nvim
export PATH=/usr/local/sbin:/usr/local/bin:~/bin:$PATH

export FZF_DEFAULT_OPTS="
  --reverse
  --preview='[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2> /dev/null | head -300'
  --preview-window=right:hidden
  --bind='ctrl-w:toggle-preview,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-y:execute-silent(echo {+} | pbcopy)'
"
export FZF_DEFAULT_COMMAND='fd'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t d"

## History Settings
export HISTSIZE=100000
export HISTFILE=$HOME/.zsh_history
export SAVEHIST=$HISTSIZE
setopt EXTENDED_HISTORY      # record command time and duration
setopt HIST_FIND_NO_DUPS     # do not find duplicates in history
setopt HIST_IGNORE_ALL_DUPS  # remove older duplicate commands
setopt HIST_REDUCE_BLANKS    # leave blanks out
setopt INC_APPEND_HISTORY    # write after each command

## Aliases
alias ls='ls -G'
alias ll='ls -l'
alias v='nvim'
alias -s {csv,js,json,jsx,py,ts,tsx,txt,yml}=nvim

alias config.alacritty='v ~/.config/alacritty/alacritty.yml'
alias config.git='git config --global -e'
alias config.git.ignore='v ~/.config/git/ignore'
alias config.tmux='v ~/.tmux.conf'
alias config.tmux.reload='tmux source-file ~/.tmux.conf'
alias config.vim='v ~/.config/nvim/init.vim'
alias config.zsh.local.reload='. ~/.zshrc_local'
alias config.zsh.local='v ~/.zshrc_local'
alias config.zsh.reload='. ~/.zshrc'
alias config.zsh='v ~/.zshrc'
alias history.reload='fc -R'

alias ga='git add'
alias gb='git branch'
alias gbd='git branch -D'
alias gc='git commit'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout main'
alias gd='git diff -w'
alias gdc='git diff -w --cached'
alias gl="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git pull --prune'
alias gpdo='git push --delete origin'
alias gpom='git pull origin main'
alias gs='git status -sb'
alias gsl='git stash list'
alias gsp='git stash pop'
alias gst='git stash'

alias dc='docker-compose'
alias dc-logs='docker-compose logs -f'

top20() {
    history 1 | cat | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a; }' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl | head -n20
}

## Prompt String
PS1=' %F{yellow}%~%F{blue}$(__git_ps1) %F{reset}$ '

## Completion
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

## Startup
[ -f ~/.zshrc_local ] && source ~/.zshrc_local

if command -v tmux &> /dev/null &&  # tmux is installed
  [ -n "$PS1" ] &&                  # in interactive shell
  [ -z "$TMUX" ]; then              # not in tmux session
    tmux attach || exec tmux new-session
fi

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

# Generated by Hermit; START; DO NOT EDIT.
eval "$(test -x $HOME/bin/hermit && $HOME/bin/hermit shell-hooks --print --zsh)"
# Generated by Hermit; END; DO NOT EDIT.
